// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTajtYqg-emyuM8zmd_hj_OYTa_FdxtuU',
    appId: '1:355346172285:web:f1d34414e933572a1fa414',
    messagingSenderId: '355346172285',
    projectId: 'monkey-meal',
    authDomain: 'monkey-meal.firebaseapp.com',
    storageBucket: 'monkey-meal.appspot.com',
    measurementId: 'G-E9F3FW6EWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sAaLljnT_lYozI4JrmXiROOJ4BXDrjg',
    appId: '1:355346172285:android:3bc85f2078ee9c531fa414',
    messagingSenderId: '355346172285',
    projectId: 'monkey-meal',
    storageBucket: 'monkey-meal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoxtaLuR0r2TFBEzROQrpmHhqOsDTPgrw',
    appId: '1:355346172285:ios:e782ca0199c1f2ef1fa414',
    messagingSenderId: '355346172285',
    projectId: 'monkey-meal',
    storageBucket: 'monkey-meal.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );
}
